#!/bin/sh

# This script takes the most-current state files and writes them to the
# named file.

. /usr/lib/distkv/env

set -e
test -n "$1"
F="$(python3 -c "import sys; from os.path import abspath; print(abspath(sys.argv[1]))" "$1")"

mkdir -p "$DEST"
cd "$DEST"
d=$(ls -t|head -1)
if test -z "$d" || test ! -s "$d/0.dkv" ; then
    echo "No data directory found" >&2
    exit 1
fi
cd $d

ls | grep '\.dkv$' | sort -n | xargs cat > "$TEMP"
