#!/bin/sh
set -ex

# This script sets up an initial DistKV master.

set -ex

if test -s /etc/distkv.env ; then
    echo "'/etc/distkv.env' exists, not initializing" >&2
    exit 0
fi

. /usr/lib/distkv/env

echo MODE=master >/etc/distkv.env
echo NAME=$(hostname) >>/etc/distkv.env

mkdir -p "$DEST"
cd "$DEST"
d=$(find . -name 0.dkv -size +1c | sort | head -1)
if test -z "$d" ; then
    d="$(date -d 2019-01-01 +"$DATE")"
    mkdir -p "$d"
fi
cd $d

if test ! -s "0.dkv" ; then
    distkv dump init $NAME 0.dkv
    chown -R distkv:distkv "$DEST"
fi
