#!/bin/bash
set -ex

# This script file starts up a DistKV any-node runner.

if test $# = 1 ; then
    exec distkv -c /etc/distkv.cfg client job -g "$1" all
else
    exec distkv -c /etc/distkv.cfg client job all
fi
