#!/bin/bash
set -ex

# This script file starts up a MoaT-KV single-node runner.

if test ! -v NAME ; then
    echo "NAME is not set. Exiting." >&2
    exit 1
fi

if test $# = 1 ; then
    exec moat.kv -c /etc/moat.kv.cfg client job -n "$NAME" -g "$1" run
else
    exec moat.kv -c /etc/moat.kv.cfg client job -n "$NAME" run
fi
