# command line interface

import sys
import asyncclick as click
from distkv.util import MsgReader
from functools import partial
from collections import Mapping

from distkv.util import MsgReader, MsgWriter
from distkv.util import yprint

import logging

logger = logging.getLogger(__name__)


@main.group(short_help="Manage data.")  # pylint: disable=undefined-variable
@click.pass_obj
async def cli(obj):
    """
    Low-level tools that don't depend on a running server.
    """
    pass


@cli.command()
@click.argument("path", nargs=-1)
@click.pass_obj
async def cfg(obj, path):
    """Emit the current configuration as a YAML file.
    
    You can limit the output by path elements.
    E.g., "cfg connect host" will print "localhost".

    Single values are printed with a trailing line feed.
    """
    cfg = obj.cfg
    for p in path:
        try:
            cfg = cfg[p]
        except KeyError:
            if obj.debug:
                print("Unknown:",p)
            sys.exit(1)
    if isinstance(cfg,str):
        print(cfg, file=obj.stdout)
    else:
        yprint(cfg, stream=obj.stdout)


@cli.command()
@click.argument("file", nargs=1)
@click.pass_obj
async def file(obj, file):
    """Read a MsgPack file and dump as YAML."""
    async with MsgReader(path=file) as f:
        async for msg in f:
            yprint(msg, stream=obj.stdout)
            print("---", file=obj.stdout)

@cli.command()
@click.argument("node", nargs=1)
@click.argument("file", type=click.Path(), nargs=1)
@click.pass_obj
async def init(obj, node, file):
    """Write an initial preload file.
    
    Usage: distkv dump init <node> <outfile>

    Writes an initial DistKV file that behaves as if it was generated by <node>.

    Using this command, followed by "distkv server -l <outfile> <node>", is
    equivalent to running "distkv server -i 'Initial data' <node>.
    """
    async with MsgWriter(path=file) as f:
        await f(dict(chain=dict(node=node,tick=1,prev=None),depth=0,path=[],tock=1,value="Initial data"))

@cli.command()
@click.pass_obj
async def serf(obj):
    """Monitor the Serf message stream.
    """
    from asyncserf import NoopCodec, serf_client
    import msgpack

    part_cache = {}

    async with serf_client(codec=NoopCodec(), **obj.cfg.server.serf) as client:  # pylint: disable=not-async-context-manager
        async with client.stream("*") as stream:
            async for resp in stream:
                c=vars(resp)
                c.pop('client', None)
                c.pop('coalesce', None)
                msg=c['payload']
                if c.get('event','').startswith('member-'):
                    m = partial(msgpack.unpackb,raw=True, use_list=False)
                    msg = m(msg)
                else:
                    m = partial(msgpack.unpackb,raw=False, use_list=False)
                    msg = m(msg)

                if isinstance(msg, Mapping) and "_p0" in msg:
                    p = msg["_p0"]   
                    if p != "":
                        nn, seq, i, p = p
                        s = part_cache.get((nn, seq), None)
                        if s is None:
                            part_cache[(nn,seq)] = s = [None]
                        if i < 0:
                            i = -i
                            s[0] = b""
                        while len(s) <= i:
                            s.append(None)
                        s[i] = p
                        if None in s:    
                            # yprint([nn,seq,i], stream=obj.stdout)
                            # print("---", file=obj.stdout)
                            continue
                        msg = b"".join(s)
                        del part_cache[(nn, seq)]
                        m = partial(msgpack.unpackb,raw=False, use_list=False)
                        msg = m(msg)
                
                    i = 0
                    while ("_p%d" % (i + 1)) in msg:
                        msg["_p%d" % i] = msg["_p%d" % (i + 1)]  
                        i += 1 
                    del msg["_p%d" % i]

                c['payload'] = msg

                yprint(c, stream=obj.stdout)
                print("---", file=obj.stdout)
